$ANSIBLE_VAULT;1.1;AES256
64656636366634616639623934363634623533373564633530316433313663343365383962656565
3231346530633738326237666232393039613538656333310a396466323162626331636539356166
37353265646465613565343366333236373637636134373664333661373530396134333932633633
3438306265343365660a383034316561383332373035383065643339653835306138653638333438
62393231346263383030643665393666346636636337303635366438636232383132353064623564
65396236646662316566376462376434656363333236663731353131616366663236313932623633
34653761333538666162633434316663616561333130623834386566393036343661636232303235
34306631323231323535623735643830646434386635663333323835633737376266633735616662
37383763373865663330653235303839646666303538333738343833656262346464
